# Generated by Django 2.2.12 on 2023-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_image', models.ImageField(upload_to='')),
                ('ratings', models.CharField(max_length=5)),
                ('feedback_status', models.CharField(max_length=20)),
            ],
        ),
    ]
