# Generated by Django 4.2.3 on 2023-09-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_image',
        ),
    ]
