# Generated by Django 4.2.3 on 2023-09-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={},
        ),
    ]
